---

- name: INSTALL PAYARA
  hosts: default
  become: true

  tasks:
  - name: prerequisites
    block:
    - name: create payara system group
      ansible.builtin.group:
        name: payara
        system: true

    - name: create payara system account
      ansible.builtin.user:
        name: payara
        group: payara
        comment: Payara System Account
        system: true

    - name: install openjdk
      ansible.builtin.package:
        name: "openjdk-{{openjdk_version}}-jre-headless"
        state: present

  - name: install payara server
    block:
    - name: download archive
      ansible.builtin.get_url:
        url: "https://repo1.maven.org/maven2/fish/payara/distributions/payara/{{payara_version}}/payara-{{payara_version}}.zip"
        #checksum: sha1:https://repo1.maven.org/maven2/fish/payara/distributions/payara/{{payara_version}}/payara-{{payara_version}}.zip.sha1
        dest: /tmp/payara.zip
        mode: '0600'

    - name: extract archive
      ansible.builtin.unarchive:
        src: /tmp/payara.zip
        dest: /opt
        remote_src: true

    - name: symlink folder
      ansible.builtin.file:
        src: /opt/payara5
        dest: /opt/payara
        state: link

    - name: cleanup cache
      ansible.builtin.file:
        path: "{{item}}"
        state: absent
      loop:
        - /tmp/payara.zip
        - /opt/payara/glassfish/domains/domain1/
...