---
- name: PROVISION PAYARA CONTAINER
  hosts: default
  become: true
  gather_facts: false

  tasks:
  - name:
    ansible.builtin.apt:
      update_cache: yes

  - name: install ansible and python modules
    ansible.builtin.package:
      name:
      - ansible
      - python3-lxml 
      state: present
...