# https://blog.payara.fish/back-to-basics-installing-payara-server-5-on-ubuntu
# https://www.payara.fish/payara-site/media/gb/Payara-Server-5-Administration-Cheat-Sheet-English.pdf
# https://docs.payara.fish/community/docs/5.2020.7/documentation/payara-server/README.html
---

- name: CONFIGURE PAYARA
  hosts: default
  become: true

  tasks:
  - name: CREATE ASADMIN PASSWORD
    block:
    - ansible.builtin.copy:
        content: |
          AS_ADMIN_PASSWORD=
          AS_ADMIN_NEWPASSWORD={{asadmin_password}}
        dest: /tmp/secret.txt
        mode: '0640'

    #- ansible.builtin.shell: |
    - shell:
        cmd: "/opt/payara/bin/asadmin --user admin {{item}}"
      loop:
      - "create-domain --nopassword=true {{domain_name}}"
      - "--passwordfile=/tmp/secret.txt change-admin-password --domain_name={{domain_name}}"
      
    - ansible.builtin.file:
        path: /tmp/secret.txt
        state: absent

  - name: CONFIGURE PAYARA SETTINGS
    block:
    - ansible.builtin.copy:
        content: |
          AS_ADMIN_PASSWORD={{asadmin_password}}
        dest: /opt/payara/secret.txt
        mode: '0640'

    #- ansible.builtin.shell: |
    - shell:
        cmd: |
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt start-domain {{domain_name}}
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt enable-secure-admin
          for MEMORY_JVM_OPTION in $(/opt/payara/bin/asadmin --user=admin --passwordfile=/opt/payara/secret.txt list-jvm-options | grep "Xm[sx]"); do
            /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt delete-jvm-options ${MEMORY_JVM_OPTION}
          done
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt create-jvm-options '-XX\:+UseContainerSupport:-XX\:MaxRAMPercentage=85'
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.logtoFile=false
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt stop-domain --kill=true {{domain_name}}
...