---
- name: PROVISION PAYARA CONTAINER
  hosts: default
  become: true
  gather_facts: false

  vars:
    timezone:
      continent: "{{TIMEZONE_CONTINENT|default('Europe')|string}}"
      city: "{{TIMEZONE_CITY|default('Oslo')|string}}"
    locale:
      name: "{{LOCALE_NAME|default('nb_NO ISO-8859-1')|string}}"
      language_pack: "{{LOCALE_LANGUAGE_PACKAGE|default('language-pack-nb')|string}}"
    java:
      version: "{{JAVA_VERSION|default('openjdk-11-jre-headless'|string)}}"
      max_ram: "{{JAVA_MAX_RAM|default('85')|string}}"
    payara:
      group: "{{PAYARA_GROUP|default('payara')|string}}"
      user: "{{PAYARA_USER|default('payara')|string}}"
      version_major: "{{PAYARA_VERSION_MAJOR|default('5')|string}}"
      version_minor: "{{PAYARA_VERSION_MINOR|default('2020.7')|string}}"
      domain: "{{PAYARA_DOMAIN|default('production')|string}}"
      asadmin_password: "{{PAYARA_ASADMIN_PASSWORD|default('Admin123')|string}}"

  tasks:
# -----------------------------------------------
  - name: ADD CONTAINER ENTRYPOINT
    block:
    - name: adding entrypoint script
      ansible.builtin.copy:
        src: files/docker-entrypoint.sh
        dest: /docker-entrypoint.sh
        owner: root
        group: root
        mode: '0740'
# -----------------------------------------------
  - name: SET TIMEZONE
    block:
    - name: preseeding timezone config (region)
      ansible.builtin.debconf:
        name: tzdata
        question: tzdata/Areas
        value: "{{timezone['continent']}}"
        vtype: select

    - name: preseeding timezone config (city)
      ansible.builtin.debconf:
        name: tzdata
        question: "tzdata/Zones/{{timezone['continent']}}"
        value: "{{timezone['city']}}"
        vtype: select

    - name: installing timezone package(s)
      ansible.builtin.package:
        name:
        - tzdata
        state: present
# -----------------------------------------------
  - name: ADD LOCALE
    block:
    - name: installing laguagepack(s)
      ansible.builtin.package:
        name:
        - "{{locale['language_pack']}}"
        - locales
        state: present

    - name: generating locale files
      ansible.builtin.command:
        argv:
        - /usr/sbin/locale-gen
        - "{{locale['name']}}"
# -----------------------------------------------
  - name: PAYARA PRE-INSTALL
    block:
    - name: creating payara system group
      ansible.builtin.group:
        name: "{{payara['group']}}"
        system: true

    - name: creating payara system user
      ansible.builtin.user:
        name: "{{payara['user']}}"
        group: "{{payara['group']}}"
        comment: Payara Server System Account
        system: true

    - name: installing java runtime
      ansible.builtin.package:
        name: "{{java['version']}}"
        state: present
# -----------------------------------------------
  - name: PAYARA INSTALL
    block:
    - name: downloading payara archive
      local_action:
        module: ansible.builtin.get_url
        url: "https://repo1.maven.org/maven2/fish/payara/distributions/payara/{{payara['version_major']}}.{{payara['version_minor']}}/payara-{{payara['version_major']}}.{{payara['version_minor']}}.zip"
        #checksum: sha1:https://repo1.maven.org/maven2/fish/payara/distributions/payara/{{payara['version_major']}}.{{payara['version_minor']}}/payara-{{payara['version_major']}}.{{payara['version_minor']}}.zip.sha1
        dest: "cache/payara-{{payara['version_major']}}.{{payara['version_minor']}}.zip"
        mode: '0644'
        validate_certs: false
        timeout: 30

    - name: extracting payara archive into container
      ansible.builtin.unarchive:
        src: "cache/payara-{{payara['version_major']}}.{{payara['version_minor']}}.zip"
        dest: /opt

    - name: symlinking payara folder
      ansible.builtin.file:
        src: /opt/payara{{payara['version_major']}}
        dest: /opt/payara
        state: link

    - name: removing unwanted files
      ansible.builtin.file:
        path: "{{item}}"
        state: absent
      loop:
      - /opt/payara/glassfish/domains/domain1/
# -----------------------------------------------
  - name: CREATE ASADMIN PASSWORD
    block:
    - name: creating temporary asadmin password-file
      ansible.builtin.copy:
        content: |
          AS_ADMIN_PASSWORD=
          AS_ADMIN_NEWPASSWORD={{payara['asadmin_password']}}
        dest: /tmp/secret.txt
        mode: '0640'

    #- ansible.builtin.shell: |
    - name: setting asadmin password
      shell:
        cmd: |
         /opt/payara/bin/asadmin --user admin create-domain --nopassword=true {{payara['domain']}}
         /opt/payara/bin/asadmin --user admin --passwordfile=/tmp/secret.txt change-admin-password --domain_name={{payara['domain']}}

    - name: removing temporary asadmin password-file
      ansible.builtin.file:
        path: /tmp/secret.txt
        state: absent

  - name: CONFIGURE PAYARA
    block:
    - name: creating asadmin password-file
      ansible.builtin.copy:
        content: |
          AS_ADMIN_PASSWORD={{payara['asadmin_password']}}
        dest: /opt/payara/secret.txt
        mode: '0640'

    #- ansible.builtin.shell: |
    - name: configuring payara domain
      shell:
        cmd: |
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt start-domain {{payara['domain']}}
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt enable-secure-admin
          for MEMORY_JVM_OPTION in $(/opt/payara/bin/asadmin --user=admin --passwordfile=/opt/payara/secret.txt list-jvm-options | grep "Xm[sx]"); do
            /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt delete-jvm-options ${MEMORY_JVM_OPTION}
          done
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt create-jvm-options '-XX\:+UseContainerSupport:-XX\:MaxRAMPercentage={{java['max_ram']}}'
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.logtoFile=false
          /opt/payara/bin/asadmin --user admin --passwordfile=/opt/payara/secret.txt stop-domain --kill=true {{payara['domain']}}
...