# Useful links:
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://docs.github.com/en/actions/learn-github-actions/environment-variables
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - https://github.com/marketplace/actions/build-and-push-docker-images
# - https://yaml-multiline.info/
#
# Actions Used:
# - https://github.com/docker/metadata-action
# - https://github.com/docker/setup-buildx-action
# - https://github.com/docker/login-action
# - https://github.com/marketplace/actions/build-and-push-docker-images
---
name: Payara (Public)

on:
  workflow_dispatch:

jobs:
  payara:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          registry.hub.docker.com/kdsda/payara
        tags: |
          type=edge
          type=raw,value=development
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Registry (Docker Hub)
      uses: docker/login-action@v1 
      with:
        registry: registry.hub.docker.com
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_SECRET }}
    -
      name: Build and push | 5.2021.9 | OpenJDK 17 (jre)
      uses: docker/build-push-action@v2
      with:
        context: docker
        build-args: |
          BASE_IMAGE: azul/zulu-openjdk-debian:17-jre
          PAYARA_VERSION_MAJOR: 5
          PAYARA_VERSION_MINOR: 2021.9
          EXTRA_LOCALES: nb_NO
        tags: ${{ steps.meta.outputs.tags }}
        push: false
    -
      name: Update description
      uses: peter-evans/dockerhub-description@v2
      with:
        repository: Kreditorforeningens-Driftssentral-DA/container-image-payara
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_SECRET }}
        short-description: ${{ github.event.repository.description }}
