# Useful links:
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://docs.github.com/en/actions/learn-github-actions/environment-variables
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - https://github.com/marketplace/actions/build-and-push-docker-images
# - https://yaml-multiline.info/
#
# Actions Used:
# - https://github.com/marketplace/actions/github-environment-variables-action
# - https://github.com/docker/metadata-action
# - https://github.com/docker/setup-buildx-action
# - https://github.com/docker/login-action
# - https://github.com/marketplace/actions/build-and-push-docker-images
---
name: Docker Builds - Payara (Public)

on:
  workflow_dispatch:

jobs:
  payara:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE: azul/zulu-openjdk-debian:17-jre
      PAYARA_VERSION_MAJOR: 5
      PAYARA_VERSION_MINOR: 2021.9
      EXTRA_LOCALES: nb_NO
    steps:
    - # Check out sourcecode
      name: Checkout
      uses: actions/checkout@v2
    - # Add metadata for tagging images
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: registry.hub.docker.com/kdsda/payara
        tags: |
          type=edge
          type=sha
          type=raw,value=development
    - # Use QEMU for multi-arch
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - # Enable Buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - # Login to container registry
      name: Login to Registry (Docker Hub)
      uses: docker/login-action@v1 
      with:
        registry: registry.hub.docker.com
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_SECRET }}
    - # Build container and push to registry
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker
        build-args: |
          BASE_IMAGE: ${BASE_IMAGE}
          PAYARA_VERSION_MAJOR: ${PAYARA_VERSION_MAJOR}
          PAYARA_VERSION_MINOR: ${PAYARA_VERSION_MINOR}
          EXTRA_LOCALES: ${EXTRA_LOCALES}
        tags: ${{ steps.meta.outputs.tags }}
        push: true
    #- # Update docker hub description
    #  name: Update description
    #  uses: peter-evans/dockerhub-description@v2
    #  with:
    #    repository: kdsda/payara
    #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #    password: ${{ secrets.DOCKER_HUB_SECRET }}
    #    short-description: ${{ github.event.repository.description }}
