# Actions:
# - https://github.com/marketplace/actions/build-and-push-docker-images
# - https://github.com/docker/metadata-action
# - https://github.com/docker/setup-buildx-action
# - https://github.com/docker/login-action
# - https://github.com/docker/build-push-action
---
name: Docker - Payara (Public)

on:
  workflow_dispatch:

  push:
    paths:
    - 'docker/*'

    branches:
    - main
    - develop

    tags:
    - '*.*.*'

jobs:
  payara:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
        - azul/zulu-openjdk-debian:11
        - azul/zulu-openjdk-debian:17
        version:
        - '5.2021.9'
        - '6.2021.1.Alpha1'
        # Prefix for exporting images
        include:
        - image: azul/zulu-openjdk-debian:11
          prefix: '11'
        - image: azul/zulu-openjdk-debian:17
          prefix: '17'
        # Unsupported build-combinations
        exclude:
        - image: azul/zulu-openjdk-debian:17
          version: 6.2021.1.Alpha1
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: registry.hub.docker.com/kdsda/payara
        flavor: |
          prefix=${{ matrix.prefix }}.${{ matrix.version }}-
        tags: |
          type=ref,event=branch
          type=edge
          type=sha
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Registry (Docker Hub)
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        registry: registry.hub.docker.com
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_SECRET }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker
        build-args: |
          BASE_IMAGE=${{ matrix.image }}
          PAYARA_VERSION=${{ matrix.version }}
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
