# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
name: Packer Public

on: [workflow_dispatch]

jobs:
  payara-v5-2020-7_jre-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        TARGET_BUILD: v5-2021-1_jre-11.docker
        TARGET_SOURCE: docker.UBUNTU_2004
        PKR_VAR_docker_image_name: "registry.hub.docker.com/kdsda/payara"
        PKR_VAR_docker_login_server: "registry.hub.docker.com"
        PKR_VAR_docker_login_username: "${{ secrets.DOCKER_HUB_USERNAME }}"
        PKR_VAR_docker_login_password: "${{ secrets.DOCKER_HUB_SECRET }}"
      run: |
        # [PAYARA] BUILD & PUSH TO DOCKER HUB
        set -e
        packer version
        docker --version
        ansible --version | head -n 1
        pushd src/packer
        packer validate -only=${TARGET_BUILD}.${TARGET_SOURCE} .
        packer fmt -diff -write=false .
        packer build -only=${TARGET_BUILD}.${TARGET_SOURCE} .
        popd
...
